
# Runs subcommand assign-reviewers
assign: 
	go run cmd/bot.go assign-reviewers

# Runs subcommand check-reviewers
check: 
	go run cmd/bot.go check-reviewers

# Runs all go tests
test: 
	go test ./...